### ISSUE TITLE
DBT installation fails on Windows and Linux

### ISSUE THREAD

**Issue by brylie** [dbt-labs/homebrew-dbt#14]
On both Linux and Windows, the dbt installation via pip fails with the following error:

```
RuntimeError:
    Please install pkg-config on your system or set the ICU_VERSION environment
    variable to the version of ICU you have installed.    (running 'icu-config --version')
```

This prerequisite is not documented in the debt installation instructions. The lack of documentation and subsequent error has made it difficult for myself and my colleague to get started using dbt in our organization.

**Comment by brylie** [comment]
I tried to improve the installation instructions, including how to install the pkg-config dependency.

https://github.com/fishtown-analytics/docs.getdbt.com/pull/606

Please test the documentation by observing users installing dbt on fresh operating systems. Inability to install the software and lack of clear prerequisites is making for a poor user experience.

**Comment by brylie** [comment]
The pkg-config dependency may not fully prevent dbt from being installed, as my colleague is able to run the `dbt` command despite seeing the above runtime error. In any case, it is confusing and I spent several minutes troubleshooting the issue when installing on Linux.

**Comment by jtcohen6** [comment]
Hi @brylie, thanks for opening the issue, and sorry you've run into trouble installing dbt. I appreciate your patience and interest in helping make this experience better for other users. Your points on the documentation site (https://github.com/fishtown-analytics/docs.getdbt.com/pull/606) were well taken, and I'd be happy to discuss more over there; we're trying to find the right balance between clarity for the majority of users, and thoroughness for long tail of installation cases.

As far as this specific issue, installing dbt with Homebrew and running into an error that mentions ICU, I'm wondering if this relates to a dependency issue we encountered a few weeks ago (https://github.com/fishtown-analytics/dbt/issues/3160). Could you try installing a patched version of dbt, and let me know if you encounter the same error?
```
$ brew install dbt@0.19.1-rc1
$ brew install dbt@0.18.2
```

**Comment by brylie** [comment]
@jtcohen6, the runtime error does not occur when installing dbt with the following requirements.txt on Linux:

```
dbt==0.18.*
# dbt's 3rd level dependency broken, so locking said dependency "agate" to working version 1.6.1
agate==1.6.1
```

**Comment by jtcohen6** [comment]
That's great to hear. I'm hopeful that this will not be an issue for installing either v0.18.2 or v0.19.1, for which we introduced an upper bound on `agate<1.6.2`.

**Comment by jacquiwuc** [comment]
Hey, brylie, 

I got the same error there when trying to install dbt on Windows, and installed pkg-config through  'pip install pkgconfig'. However, still same error.

Have you figured it out how to solve this? Tnx in advance.
