### ISSUE TITLE
[CT-1062] [Bug] Homebrew installation test failure on ubuntu

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/homebrew-dbt#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Opening an issue for the conversation with @kyleries [here](https://github.com/dbt-labs/homebrew-dbt/pull/161#issuecomment-1220996752).

The recent fix purposed for brew install of [stop use system site packages](https://github.com/dbt-labs/homebrew-dbt/pull/161) by @kyleries works perfectly locally on my macbook but still causing the integration test failing.

We can use this issue to track the conversation around CI improvements on testing brew install.

**Comment by ChenyuLInx** [comment]
Findings:
Currently, the integration test is failing due to not being able to the following error:
```
  c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
      2 | #include <Python.h>
        |          ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc-10' failed with exit status 1
```
Looks like this is because `python-dev` / `python3-dev` not installed.
After a bit searching, when using brew on macbook, we should already have it. ([reference](https://stackoverflow.com/questions/32578106/how-to-install-python-devel-in-mac-os))

Checking our `workflow` [definition](https://github.com/dbt-labs/homebrew-dbt/blob/main/.github/workflows/installation-tests.yml#L29), we are currently running these tests with Ubuntu images.

So seems like we should probably:
1. add the macOS test environment in CI. @kyleries I think you also mentioned this somewhere.
2. add special instruction in workflow definition to handle the case for Ubuntu user? I am guessing the new fix in #161 might introduced this issue?

**Comment by ChenyuLInx** [comment]
For now it is best for ubuntu users to use pip install

**Comment by leahwicz** [comment]
@ChenyuLInx I can add macOS to the testing GitHub Action today if that is something we want to do.

**Comment by kyleries** [comment]
I did a bit of research on the Ubuntu issue - I think I have a theory and possible solution, but I haven't coded anything up yet, all in the gray matter ( 🧠 ) at the moment. In short though - and perhaps unsurprisingly - it comes down to solving for the dependency issue, and I think I'm going to experiment w/ some settings in `dbt_extractor` to specify a stricter requirement.

**Comment by jtcohen6** [comment]
Thanks for all your help over the past several days @kyleries!

For now, we want to prioritize offering Homebrew as a user-friendly (if slow) installation mechanism on MacOS. It would be great to get it working on Linux/Ubuntu as well, but it's not something we're going to prioritize ourselves. You're welcome to keep jamming on it as you'd like to!

**Comment by kyleries** [comment]
Sounds good, thanks @jtcohen6 for the clarification. I interpreted the CI setup running only on Ubuntu to be a signal of priority, but def makes sense to me to target Home-brew for the Mac crew. Now that Mac OS has been added to the CI config, that's a solid sign.

**Comment by leahwicz** [comment]
This is now working for Ubuntu as well for Mac now but with no changes from our side so I'm assuming a dependency broke something and then fixed it. I'm going to close this issue out and thanks @kyleries for your help and guidance here. We have been looking into bottling these formulas to avoid this in the future but just haven't had the bandwidth but will look again at prioritizing if possible
