### ISSUE TITLE
[CT-1124] [Bug] dbt does not cache SSO token

### ISSUE THREAD

**Issue by RoyalTS** [dbt-labs/homebrew-dbt#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Several people over at `dbt-snowflake`, who have installed that package via homebrew are [reporting that dbt no longer caches the SSO token](https://github.com/dbt-labs/dbt-snowflake/issues/208#issuecomment-1237364680) and they are therefore being innundated with requests to authorize. This seems to be an issue with the homebrew install rather than with the underlying Python package.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What Homebrew formula are you trying to install?

snowflake

**Comment by jtcohen6** [comment]
Sorry for the delay following up @RoyalTS!

@EstelleBarnoud offered a solid explanation for what's going on, and a way to (hopefully) get this working, in the linked issue: https://github.com/dbt-labs/dbt-snowflake/issues/208#issuecomment-1372936000

I'm going to close this one for now.
