### ISSUE TITLE
[CT-1435] [Bug] GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by kevinneville** [dbt-labs/homebrew-dbt#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GitHub Actions: Deprecating save-state and set-output commands, these should be replaced with the proposed solution.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### Expected Behavior

We should not see the warnings.

### Steps To Reproduce

Run all GH checks.

### Environment

```markdown
- OS:
- Python:
- dbt:
```

**Comment by jtcohen6** [comment]
Thanks @kevinneville!
