### ISSUE TITLE
[CT-1706] [Feature] Add `dbt-spark` to the Homebrew nightly integration test

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/homebrew-dbt#193]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

While troubleshooting https://github.com/dbt-labs/homebrew-dbt/issues/253, it seems like dbt-spark is not covered. We should add it!

**Comment by emmyoop** [comment]
We don't release spark with homebrew so this isn't needed.
