### ISSUE TITLE
Crazy long install time??

### ISSUE THREAD

**Issue by lazarillo** [dbt-labs/homebrew-dbt#20]
I just installed DBT:

```==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt-20210923-6219-60xetl/dbt-0.20.2
🍺  /usr/local/Cellar/dbt/0.20.2_1: 9,872 files, 163.0MB, built in 15 minutes 20 seconds
```

Is that *normal*:  **15 minutes** to `brew install dbt`?

**Comment by drewbanin** [comment]
hey @lazarillo - can you tell us which version of macOS you're using and whether or not it's one of the M1 machines? We build "bottles" that should be pre-compiled for different OS's, but if there isn't a match between your system and a pre-built bottle, then installation of dbt is going to require a slow compilation process on your machine :/

Let us know and we can check it out!

**Comment by jtcohen6** [comment]
I think one of the big contributors to the slow install time is dbt-core now requiring a Rust program dependency ([`dbt-extractor`](https://github.com/dbt-labs/dbt-extractor)). We do build pre-compiled wheels of that dependency for most system architectures, which speeds up `pip install dbt-core` significantly. By default, however, Homebrew does not like installing from wheels—it prefers to build everything from source—which, in this case, requires installing a Rust compiler.

@kwigley Could you please correct me if I got the details there wrong? And  perhaps advise on if there exists a sensible way to override the Homebrew formula to install `dbt-extractor` from wheel when available?

**Comment by ffoxdd** [comment]
I'm getting crazy long install times too on macOS 11.6, non-M1.

Looks like it's doing a bunch of pip installs that each take forever `==> Installing dbt-labs/dbt/dbt
==> python3 -m venv --system-site-packages /usr/local/Cellar/dbt/0.20.2_1/libexec
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install --upgrade pip
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--aga
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--asn
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--att
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--azu
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--azu
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--azu
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--Bab
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--bot
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--bot
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cac
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cer
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cff
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cha
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cha
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--col
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cry
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--dbt
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--goo
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--grp
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--hol
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--idn
==> /usr/local/Cellar/dbt/0.20.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--imp
`

**Comment by lazarillo** [comment]
Sorry, here are my details:

❯ uname -a
Darwin c02c2147md6v-c 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Comment by jtcohen6** [comment]
I believe this issue is the same as https://github.com/dbt-labs/homebrew-dbt/issues/47, and our best bet is to prefer wheels for many dependencies (but especially `dbt-extractor`) on systems where there are available
