### ISSUE TITLE
[CT-1797] [Spike] Do we need to maintain our own tap?

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/homebrew-dbt#263]
### Describe the Spike

Currently, we maintain our own tap on Homebrew.  Do we need to?

(I think) This is because the patch versions between `dbt-core` and `dbt-redshift` (or any other adapter) do not always match.  We only guarantee a match down to the minor version.  We often release a patch to `dbt-core` without a patch to any adapters.  Because of this, if we patch `dbt-core`, the adapters will not pick up the new patch if they are not also releasing a patch.  This is not an issue when using our own tap since that's checking out our git repo directly.

Previously, there was an issue with Homebrew trying to install with Python2.7 but that seems to have been [resolved](https://docs.brew.sh/Homebrew-and-Python).

It's possible this isn't a blocker anymore.  The outcome of this spike should be to determine if we need to continue maintaining our own tap and the pros/cons are of doing so.

**Comment by nathaniel-may** [comment]
Preferred to have an alternative terminal installation to brew all together. Secondary solution would be to move tap control to homebrew as outlined in this ticket.
