### ISSUE TITLE
[Bug] Missing Homebrew releases for dbt-redshift

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/homebrew-dbt#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looking at [this](https://github.com/dbt-labs/homebrew-dbt/tree/3afe5f44086a9275d802ad8d9daaf0f0d2de708a/Formula) list, the most recent for dbt-redshift is `dbt-redshift@1.4.0.rb` whereas dbt-postgres has the following:
- dbt-postgres@1.5.0-rc1.rb
- dbt-postgres@1.5.0.rb

The closed pull requests for dbt-redshift look like this:
https://github.com/dbt-labs/homebrew-dbt/pulls?q=is%3Apr+dbt-redshift+formula+for+version+is%3Aclosed

But for dbt-postgres looks like this:
https://github.com/dbt-labs/homebrew-dbt/pulls?q=is%3Apr+dbt-postgres+formula+for+version+is%3Aclosed+

### Expected Behavior

Expected homebrew formulae for dbt-redshift 1.5.0

### Environment

```markdown
- OS:
- Python:
- dbt:
```

### What Homebrew formula are you trying to install?

redshift

### Additional Context

https://getdbt.slack.com/archives/C37J8BQEL/p1684340429471609?thread_ts=1682627562.742869&cid=C37J8BQEL

**Comment by mikealfare** [comment]
It looks like we've resolved this. `dbt-redshift` aligns with PyPI up through 1.5.12 (current as of today for 1.5).
