### ISSUE TITLE
[Bug] Missing BigQuery 1.5.1 Release

### ISSUE THREAD

**Issue by codigo-ergo-sum** [dbt-labs/homebrew-dbt#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm not seeing any formulae for dbt-bigquery 1.5.1 even though it's available through dbt cloud and pypi. Possible to add this?

### Expected Behavior

That when I run `brew install dbt-bigquery@1.5.1` it would install successfully instead of getting this error message:

```
josh@Joshs-MBP-5 op-analytics % brew install dbt-bigquery@1.5.1
Warning: No available formula with the name "dbt-bigquery@1.5.1". Did you mean dbt-bigquery@1.4.1, dbt-bigquery@1.5.0, dbt-bigquery@1.5.0-rc1, dbt-bigquery@1.1.0, dbt-bigquery@1.1.1, dbt-bigquery@1.0.0, dbt-bigquery@1.3.0, dbt-bigquery@1.4.0, dbt-bigquery@1.4.3, dbt-bigquery@1.2.0, dbt-bigquery, dbt-bigquery@1.0.0-b1, dbt-bigquery@1.3.0-b1, dbt-bigquery@1.2.0-rc1 or dbt-bigquery@1.1.0-rc1?
==> Searching for similarly named formulae and casks...
==> Formulae
dbt-labs/dbt/dbt-bigquery@1.4.1         dbt-labs/dbt/dbt-bigquery@1.0.0         dbt-labs/dbt/dbt-bigquery ✔
dbt-labs/dbt/dbt-bigquery@1.5.0         dbt-labs/dbt/dbt-bigquery@1.3.0         dbt-labs/dbt/dbt-bigquery@1.0.0-b1
dbt-labs/dbt/dbt-bigquery@1.5.0-rc1     dbt-labs/dbt/dbt-bigquery@1.4.0         dbt-labs/dbt/dbt-bigquery@1.3.0-b1
dbt-labs/dbt/dbt-bigquery@1.1.0         dbt-labs/dbt/dbt-bigquery@1.4.3         dbt-labs/dbt/dbt-bigquery@1.2.0-rc1
dbt-labs/dbt/dbt-bigquery@1.1.1         dbt-labs/dbt/dbt-bigquery@1.2.0         dbt-labs/dbt/dbt-bigquery@1.1.0-rc1

To install dbt-labs/dbt/dbt-bigquery@1.4.1, run:
  brew install dbt-labs/dbt/dbt-bigquery@1.4.1
```

### Steps To Reproduce

Run `brew install dbt-bigquery@1.5.1`

### Relevant log output

```shell
See above
```

### Environment

```markdown
- OS: Mac OS 13.3.1 (a)
- Python: Python 3.9.6
- dbt: N/A, see above
```

### What Homebrew formula are you trying to install?

bigquery

**Comment by dbeatty10** [comment]
Thanks for reporting this @codigo-ergo-sum 🙏

We did a release of [dbt-bigquery@1.5.1](https://github.com/dbt-labs/homebrew-dbt/blob/0f51e60a3d518062e5fb1974b4f9b8b4808ce704/Formula/dbt-bigquery%401.5.1.rb) earlier today.

Could you give it a shot and see if it works?

**Comment by codigo-ergo-sum** [comment]
Thanks @dbeatty10 . I just tested and yes, was able to successfully download and install dbt-core 1.5.1 and dbt-bigquery 1.5.1 via `brew update` just now. Closing this ticket.
