### ISSUE TITLE
[Bug] Installs fail with `No module named pip`/ No formula found

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/homebrew-dbt#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Multiple dbt-* package installs failing with:
```
/opt/homebrew/Cellar/dbt-redshift@1.4.0/1.4.0/libexec/bin/python
-m
pip
install
pip==22.3.1
/opt/homebrew/Cellar/dbt-redshift@1.4.0/1.4.0/libexec/bin/python: No module named pip
```

**Comment by skopendoor** [comment]
I face the same issue with brew install dbt-snowflake

**Comment by dansmith-fastly** [comment]
Couldn't get upgrade to work, and now trying `brew install dbt-bigquery@1.5.0 `and getting same error

**Comment by colin-rogers-dbt** [comment]
We _think_ this is related to a change brew made (hence why it's broken even older formulas). Testing a fix now
https://github.com/Homebrew/homebrew-core/issues/15746#issuecomment-316292316

**Comment by colin-rogers-dbt** [comment]
regenerated formulas, after a `brew update` I am able to install `dbt-snowflake` and `dbt-postgres`

**Comment by sean-lynch** [comment]
I'm still running into the same issue after `brew update`. Anything else I could try?
