### ISSUE TITLE
Problem installing dbt on Mac

### ISSUE THREAD

**Issue by shrirang-joshi** [dbt-labs/homebrew-dbt#49]
I am running : brew install dbt

Get this error:
Last 15 lines from /Users/shrirang/Library/Logs/Homebrew/dbt/24.pip:
    network failure seems to have happened
    if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
    https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

  Caused by:
    remote error:
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    ; class=Net (12)
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/tmp/pip-modern-metadata-2qje8l00', '--interpreter', '/usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /private/tmp/pip-modern-metadata-2qje8l00 --interpreter /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3`
  Preparing metadata (pyproject.toml): finished with status 'error'
WARNING: Discarding file:///private/tmp/dbt--dbt-extractor-20211102-84823-7ims8q/dbt_extractor-0.4.0. Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3 /usr/local/Cellar/dbt/0.21.0_1/libexec/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmppc_8l1c5 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.0_1/libexec/bin/python3 /usr/local/Cellar/dbt/0.21.0_1/libexec/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /private/tmp/tmppc_8l1c5 Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dbt-labs/homebrew-dbt/issues

**Comment by loomalaine** [comment]
I get this as well : (

**Comment by jtcohen6** [comment]
@shrirang-joshi @loomalaine Are you running on M1 Macs? If so, we recommend you try installing via Homebrew + Rosetta instead: https://hackernoon.com/apple-m1-chip-how-to-install-homebrew-using-rosetta-su12331b

**Comment by shrirang-joshi** [comment]
I am using intel based MBP

**Comment by loomalaine** [comment]
I have a 2019 era Macbook Pro, not an M1. However, I upgraded my OS to
Monterey and that seems to have solved this problem.

[image: The Looma Project] <https://theloomaproject.com/>
Elaine McVey
‌
VP of Data Science
‌
M (919) 272-8013 <+19192728013>
‌
E ***@***.***
‌
[image: Vimeo] <https://vimeo.com/theloomaproject> [image: Instagram]
<https://www.instagram.com/loomaproject/> [image: LinkedIn]
<https://www.linkedin.com/company/the-looma-project/>

**Comment by mediix** [comment]
Apple M1 Max and I'm experiencing the same over here.

Any update?

**Comment by TimdenE** [comment]
Same issue on Intel Core i7 running Monterey 12.1 — related to the changes here? https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by dlawrences** [comment]
Same here, MacBook Pro running on Big Sur 11.6 and Intel Core i5

**Comment by kwigley** [comment]
hey y'all, I was able to track down a fix for the root issue in an upstream dependency of dbt-core (https://github.com/dbt-labs/dbt-extractor/pull/43) that will fix this issue in future versions of dbt. I haven't quite figured out a defacto workaround for installing existing version of dbt with Homebrew, but I'll be sure to update here. 

If this is a complete blocker for anyone here, a current workaround is to use `pip` to install dbt (https://docs.getdbt.com/dbt-cli/install/pip). Otherwise, trying what GitHub recommends [here](https://github.blog/2021-09-01-improving-git-protocol-security-github/#standard-git-client) may resolve this issue for you (note: I have not tried this fix!)

**Comment by TimdenE** [comment]
Otherwise, trying what GitHub recommends [here](https://github.blog/2021-09-01-improving-git-protocol-security-github/#standard-git-client) may resolve this issue for you (note: I have not tried this fix!)

Thanks @kwigley ! This seemed to work for me.

**Comment by kwigley** [comment]
I merged a change (https://github.com/dbt-labs/homebrew-dbt/pull/66) to attempt to workaround this issue. Sorry for the frustration. If anyone is still experiencing this please reach out and I can reopen this issue!
