### ISSUE TITLE
dbt fails with "image not found"

### ISSUE THREAD

**Issue by johnpkennedy** [dbt-labs/homebrew-dbt#5]
Today, I encountered this error when I ran dbt:

```
% dbt
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/dbt/0.17.0_1/libexec/bin/python3.7
  Reason: image not found
zsh: abort      ./dbt
```

The night before, I had performed a `brew update` and `brew upgrade`. I don't recall the specifics of the upgrades but everything was successful.

I'm using macOS 10.15.5 with the following python versions:

python --version: Python 2.7.16
python3 --version: Python 3.8.3

dbt has always been installed and upgraded via homebrew.

`brew doctor` reports `Your system is ready to brew.`

I have both `python@3.7` and `python@3.8` installed via homebrew.

I noticed in the `/usr/local/Cellar/dbt/0.17.0_1/libexec` directory there is a symlink named `.Python`. It is pointing to an incorrect path:

```
% ls -la .Python
lrwxr-xr-x  1 john  staff  70  8 Jun 13:13 .Python -> ../../../../opt/python/Frameworks/Python.framework/Versions/3.7/Python
```

Here's the contents of the `/usr/local/opt/python/Frameworks/Python.framework/Versions` directory:

```
% ls -la
total 0
drwxr-xr-x  4 john  staff  128 13 May 15:59 .
drwxr-xr-x  6 john  staff  192 13 May 15:59 ..
drwxr-xr-x  9 john  staff  288 13 May 15:59 3.8
lrwxr-xr-x  1 john  staff    3 13 May 15:59 Current -> 3.8
```

There is no 3.7 directory.

I uninstalled python@3.7, python@3.8, and dbt. I then reinstalled dbt (which reinstalled python@3.8). No luck. Same problem.

**Comment by drewbanin** [comment]
hey @johnpkennedy - thanks for opening this issue. We think homebrew changed their default Python from 3.7 to 3.8 which appears to have bricked existing dbt distributions on Homebrew.

We're going to address this in our next release of dbt (v0.17.1) and for the time being, you can try installing the latest RC which should also resolve this issue:

```
brew install dbt@0.17.1-rc4
```

We're still digging into what our options are to prevent this from happening again. If you have any good/informed ideas, we'd certainly love to hear about them!

**Comment by mgenereu** [comment]
The symlink `/usr/local/Cellar/dbt@0.17.1-rc4/0.17.1rc4_1/libexec/.Python` should point to
`../../../../opt/python/Frameworks/Python.framework/Versions/Current/Python`
instead of
`../../../../opt/python/Frameworks/Python.framework/Versions/3.7/Python`
or 
`../../../../opt/python/Frameworks/Python.framework/Versions/3.8/Python`

Is this something that homebrew linked automatically?
