### ISSUE TITLE
dbt 0.21.1 not installing

### ISSUE THREAD

**Issue by matfiorlh** [dbt-labs/homebrew-dbt#55]
```
Last 15 lines from /Users/mfiorillo/Library/Logs/Homebrew/dbt/23.pip:
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from https://pypi.org/simple/tomli/) (requires-python:>=3.6) is already being built: tomli>=1.2.1 from https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from setuptools-rust>=0.11.4)
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442 (from https://pypi.org/simple/tomli/) (requires-python:>=3.6). Command errored out with exit status 2: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-flroe0p_/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-mhtrq67y/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core>=3.2.0,<4' Check the logs for full command output.
  Collecting setuptools-rust>=0.11.4
    Downloading setuptools-rust-1.0.0.tar.gz (279 kB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/22/fa/ac431f0571bd84d8da5b55d9c9a00d510ae8682324405eabd96a752d090c/setuptools-rust-1.0.0.tar.gz#sha256=eb6e6d41f01e63d042288e5c609684adf93426c10ea745ec324263f3fcbf27e9 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.
  Installing build dependencies: finished with status 'error'
WARNING: Discarding file:///private/tmp/dbt--cryptography-20211130-27052-13nrzwb/cryptography-3.4.8. Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-flroe0p_/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-ufq4ws_x/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-flroe0p_/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-ufq4ws_x/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
```

**Comment by snouhaud** [comment]
Same here (macOS 11.6.1):

```
==> /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt--cryptography-20211130-24116-1lnbnui/cryptography-3.4.8
Last 15 lines from /Users/snouhaud/Library/Logs/Homebrew/dbt/23.pip:
      File "/private/tmp/pip-standalone-pip-8bllwhjf/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 92, in add
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from https://pypi.org/simple/tomli/) (requires-python:>=3.6) is already being built: tomli>=1.2.1 from https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from setuptools-rust>=0.11.4)
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442 (from https://pypi.org/simple/tomli/) (requires-python:>=3.6). Command errored out with exit status 2: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-8bllwhjf/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-nfzta72k/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core>=3.2.0,<4' Check the logs for full command output.
  Collecting setuptools-rust>=0.11.4
    Downloading setuptools-rust-1.0.0.tar.gz (279 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/22/fa/ac431f0571bd84d8da5b55d9c9a00d510ae8682324405eabd96a752d090c/setuptools-rust-1.0.0.tar.gz#sha256=eb6e6d41f01e63d042288e5c609684adf93426c10ea745ec324263f3fcbf27e9 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.
  Installing build dependencies: finished with status 'error'
WARNING: Discarding file:///private/tmp/dbt--cryptography-20211130-24116-1lnbnui/cryptography-3.4.8. Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-8bllwhjf/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-1247k_we/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-8bllwhjf/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-1247k_we/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/fishtown-analytics/homebrew-dbt/issues

Error: Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}]

```

**Comment by matfiorlh** [comment]
@snouhaud I fixed it by pushing back the version of cryptography to 3.3.2 in the dbt.rb file. Is not pretty but it works.

**Comment by RahavanRaman** [comment]
> 

Can you please elaborate on how you fixed this?

**Comment by antongoncharuk** [comment]
Same here:
___
Last 15 lines from /Users/mozart/Library/Logs/Homebrew/dbt/23.pip:
      File "/private/tmp/pip-standalone-pip-y4nm_qmm/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 92, in add
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from https://pypi.org/simple/tomli/) (requires-python:>=3.6) is already being built: tomli>=1.2.1 from https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from setuptools-rust>=0.11.4)
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442 (from https://pypi.org/simple/tomli/) (requires-python:>=3.6). Command errored out with exit status 2: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-y4nm_qmm/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-t2j0dcl9/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core>=3.2.0,<4' Check the logs for full command output.
  Collecting setuptools-rust>=0.11.4
    Downloading setuptools-rust-1.0.0.tar.gz (279 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/22/fa/ac431f0571bd84d8da5b55d9c9a00d510ae8682324405eabd96a752d090c/setuptools-rust-1.0.0.tar.gz#sha256=eb6e6d41f01e63d042288e5c609684adf93426c10ea745ec324263f3fcbf27e9 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.
  Installing build dependencies: finished with status 'error'
WARNING: Discarding file:///private/tmp/dbt--cryptography-20211201-47948-1ezpgre/cryptography-3.4.8. Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-y4nm_qmm/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-kaec9_e_/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt/0.21.1_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-y4nm_qmm/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-kaec9_e_/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.

**Comment by kristoffergr** [comment]
Here is a patch for the workaround mentioned by @matfiorlh above, to apply to the file
`/usr/local/Homebrew/Library/Taps/fishtown-analytics/homebrew-dbt/Formula/dbt.rb`
Once applied, run `brew install dbt` again and it should work.

```
diff --git a/Formula/dbt.rb b/Formula/dbt.rb
index 060346d..f9db68b 100644
--- a/Formula/dbt.rb
+++ b/Formula/dbt.rb
@@ -118,9 +118,9 @@ class Dbt < Formula
     sha256 "5941b2b48a20143d2267e95b1c2a7603ce057ee39fd88e7329b0c292aa16869b"
   end
 
-  resource "cryptography" do # cryptography==3.4.8
-    url "https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz"
-    sha256 "94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c"
+  resource "cryptography" do # cryptography==3.3.2
+    url "https://files.pythonhosted.org/packages/d4/85/38715448253404186029c575d559879912eb8a1c5d16ad9f25d35f7c4f4c/cryptography-3.3.2.tar.gz"
+    sha256 "5a60d3780149e13b7a6ff7ad6526b38846354d11a15e21068e57073e29e19bed"
   end
 
   resource "dbt-extractor" do # dbt-extractor==0.4.0
```

**Comment by matfiorlh** [comment]
Thanks @kristoffergr. for some reasons at the end it refuses to symlink but I am scared to do it manually since I do want to keep it working even on an older version.

**Comment by erika-e** [comment]
I did go ahead and relink it and looks like everything is ok. Here is the output before and after:

```zsh
➜  Formula git:(master) ✗ brew link --overwrite --dry-run dbt
Would remove:
/usr/local/bin/dbt


➜  Formula git:(master) ✗ dbt --version                                                                                                         
installed version: 0.21.0
   latest version: 0.21.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.21.0


➜  Formula git:(master) ✗ brew link --overwrite dbt          
Linking /usr/local/Cellar/dbt/0.21.1_1... 1 symlinks created.


➜  Formula git:(master) ✗ dbt --version
installed version: 0.21.1
   latest version: 0.21.1

Up to date!

Plugins:
  - bigquery: 0.21.1
  - snowflake: 0.21.1
  - redshift: 0.21.1
  - postgres: 0.21.1
  ```

**Comment by leahwicz** [comment]
@kristoffergr 's and @matfiorlh thanks so much for the resolution! 

It looks like that fixed things from my side but if anyone else is seeing the issue still, please let me know.

**Comment by snouhaud** [comment]
Look like the tip do the job well for me too. thanks a lot for your help

**Comment by amunoz444** [comment]
I stumbled across this while trying to install 0.21.0 via homebrew on Big Sur 11.6. It seems like the [fix](https://github.com/dbt-labs/homebrew-dbt/pull/57) that was put in (basically the resolution proposed above) allowed me to install 0.21.1 without any problems but 0.21.0 (which I'd prefer as it matches our dbt cloud environment) still fails:

> ==> /usr/local/Cellar/dbt@0.21.0/0.21.0_1/libexec/bin/pip install -v --no-deps --no-binary :all: --i
Last 15 lines from /Users/anthonymunoz/Library/Logs/Homebrew/dbt@0.21.0/23.pip:
      File "/private/tmp/pip-standalone-pip-a7j7hi_3/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 92, in add
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from https://pypi.org/simple/tomli/) (requires-python:>=3.6) is already being built: tomli>=1.2.1 from https://files.pythonhosted.org/packages/aa/5b/62165da80cbc6e1779f342234c7ddc6c6bc9e64cef149046a9c0456f912b/tomli-1.2.2.tar.gz#sha256=c6ce0015eb38820eaf32b5db832dbc26deb3dd427bd5f6556cf0acac2c214fee (from setuptools-rust>=0.11.4)
    ----------------------------------------
  WARNING: Discarding https://files.pythonhosted.org/packages/75/50/973397c5ba854445bcc396b593b5db1958da6ab8d665b27397daa1497018/tomli-1.2.1.tar.gz#sha256=a5b75cb6f3968abb47af1b40c1819dc519ea82bcc065776a866e8d74c5ca9442 (from https://pypi.org/simple/tomli/) (requires-python:>=3.6). Command errored out with exit status 2: /usr/local/Cellar/dbt@0.21.0/0.21.0_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-a7j7hi_3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-ckblk0e4/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'flit_core>=3.2.0,<4' Check the logs for full command output.
  Collecting setuptools-rust>=0.11.4
    Downloading setuptools-rust-1.1.0.tar.gz (284 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
  ERROR: Some build dependencies for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/a1/00/56ed41e98bd83e8fd028e24144e20bef87cdec0110fd1729352fce33d36c/setuptools-rust-1.1.0.tar.gz#sha256=e8a65f7398028cb0e4e00730ee3d1e168bf9d4e3770a61fec815e8e7a24dcab1 conflict with the backend dependencies: setuptools_scm==6.0.1 is incompatible with setuptools_scm>=6.3.2.
  Installing build dependencies: finished with status 'error'
WARNING: Discarding file:///private/tmp/dbtA0.21.0--cryptography-20211201-80974-1yraumn/cryptography-3.4.8. Command errored out with exit status 1: /usr/local/Cellar/dbt@0.21.0/0.21.0_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-a7j7hi_3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-gsl3rxwb/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt@0.21.0/0.21.0_1/libexec/bin/python3 /private/tmp/pip-standalone-pip-a7j7hi_3/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-gsl3rxwb/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel 'cffi>=1.12; platform_python_implementation != '"'"'PyPy'"'"'' 'setuptools-rust>=0.11.4' Check the logs for full command output.

**Comment by amunoz444** [comment]
0.21.0 works for me now thanks!
