### ISSUE TITLE
Issue Installing dbt-snowflake on Mac

### ISSUE THREAD

**Issue by christopher-leigh** [dbt-labs/homebrew-dbt#67]
running into this error when trying to install dbt-snowflake on mac. I have a macbook pro 2019 running Big Sur

```
    error: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.500.dylib'
    Running setup.py install for snowflake-connector-python: finished with status 'error'
ERROR: Command errored out with exit status 1: /usr/local/Cellar/dbt-snowflake/1.0.0_1/libexec/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/dbt-snowflake--snowflake-connector-python-20220120-62107-52s0g0/snowflake-connector-python-2.7.1/setup.py'"'"'; __file__='"'"'/private/tmp/dbt-snowflake--snowflake-connector-python-20220120-62107-52s0g0/snowflake-connector-python-2.7.1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-jwa1h7ee/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/dbt-snowflake/1.0.0_1/libexec/include/site/python3.9/snowflake-connector-python Check the logs for full command output.
```

**Comment by modi95** [comment]
Same issue on a 2021 MBP running Big Sur

**Comment by akomisarek** [comment]
I am not sure if my issue is related but I am having issues with dbt-snowflake as well :(, here are the relevant logs:

➜  ~ brew tap dbt-labs/dbt (no output, I guess I am on latest 
➜  ~ brew update
Already up-to-date.

Running: ➜  ~ brew install --verbose dbt

Ends up with: 

`==> /usr/local/Cellar/dbt-snowflake/1.1.0/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt-snowflake--cryptography-20220512-61084-1u68ttg/cryptography-3.4.8
Using pip 22.1 from /usr/local/Cellar/dbt-snowflake/1.1.0/libexec/lib/python3.9/site-packages/pip (python 3.9)
Processing /private/tmp/dbt-snowflake--cryptography-20220512-61084-1u68ttg/cryptography-3.4.8
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=40.6.0
    Using cached setuptools-62.2.0.tar.gz (2.5 MB)
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting wheel
    Using cached wheel-0.37.1.tar.gz (66 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting cffi>=1.12
    Downloading cffi-1.15.0.tar.gz (484 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 484.1/484.1 kB 285.5 kB/s eta 0:00:00
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting setuptools-rust>=0.11.4
    Downloading setuptools-rust-1.3.0.tar.gz (285 kB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 285.7/285.7 kB 473.7 kB/s eta 0:00:00
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'error'
    (....)
          × pip subprocess to install build dependencies did not run successfully.
          │ exit code: 2
          ╰─> [93 lines of output]
              Collecting setuptools>=45
      (...)        
             Collecting pyparsing!=3.0.5,>=2.0.2
                Downloading pyparsing-3.0.9.tar.gz (2.0 MB)
                   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 3.8 MB/s eta 0:00:00
                Installing build dependencies: started
                Installing build dependencies: finished with status 'done'
                Getting requirements to build wheel: started
                Getting requirements to build wheel: finished with status 'done'
              ERROR: Exception:
              Traceback (most recent call last):
    File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
                  status = run_func(*args)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_internal/cli/req_command.py", line 205, in wrapper
                  return func(self, options, args)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_internal/commands/install.py", line 340, in run
                  requirement_set = resolver.resolve(
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
                  result = self._result = resolver.resolve(
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
                  state = resolution.resolve(requirements, max_rounds=max_rounds)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 373, in resolve
                  failure_causes = self._attempt_to_pin_criterion(name)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 213, in _attempt_to_pin_criterion
                  criteria = self._get_updated_criteria(candidate)
              (...)  
  File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/packaging/markers.py", line 304, in evaluate
                  return _evaluate_markers(self._markers, current_environment)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/packaging/markers.py", line 234, in _evaluate_markers
                  lhs_value = _get_env(environment, lhs.value)
                File "/private/tmp/pip-standalone-pip-d0r2hqe3/__env_pip__.zip/pip/_vendor/packaging/markers.py", line 215, in _get_env
                  raise UndefinedEnvironmentName(
              pip._vendor.packaging.markers.UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
              [end of output]

          note: This error originates from a subprocess, and is likely not a problem with pip.
        error: subprocess-exited-with-error

        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 2
        ╰─> See above for output.    
`

I am not sure if this is strictly related to dbt-snowflake, but I am lost. Tried googling the 'extra' issue, but to no avail! 
Thanks!

**Comment by crysensible** [comment]
You can try using pip3 to install it. That seemed to work for me instead of using brew.
