### ISSUE TITLE
Had to re-tap to get latest patch

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/homebrew-dbt#69]
I had an odd experience when trying to upgrade from v1.0.0 &rarr; v1.0.1, whereby:
- `brew upgrade dbt-postgres` said up to date
- `brew install dbt-postgres@1.0.1` said no version found
- `brew reinstall dbt-postgres` re-installed v1.0.0

I ended up fixing by re-tapping:
```
brew untap dbt-labs/dbt --force
brew tap dbt-labs/dbt
brew install dbt-postgres
```
That successfully installed `dbt-postgres==1.0.1`. I'm willing to believe that this was just a one-time pain. I don't remember the last time I upgraded Homebrew, and it's possible my installation was actually of `dbt-redshift` or `dbt-snowflake`. Something to keep our eyes out for as we continue to release new patch versions.

**Comment by kwigley** [comment]
Thanks for this @jtcohen6. I think a `brew update` before `brew upgrade` might of fixed this for you. This is a nuance with Homebrew that I mix up all the time. It helps to keep in mind that Homebrew taps and formula are just files tracked in a git repo on your computer at the end of the day. `brew update` updates the git repo with the homebrew formulas on you computer, but doesn't install anything. `brew upgrade` will update the actual packages installed on you computer to match the same version at the formula files in the homebrew git repo. I'm hoping next time someone runs into this that this may help. I also buy that the different database adapter formulas create confusion and it is not a typical pattern for Homebrew (https://github.com/dbt-labs/homebrew-dbt/issues/68).

**Comment by jtcohen6** [comment]
I think you're probably right! Even then I knew I was getting confused between `update` and `upgrade`
