### ISSUE TITLE
Issue installing CLI with Homebrew

### ISSUE THREAD

**Issue by gboro54** [dbt-labs/homebrew-dbt#7]
While trying to install DBT 
` brew install dbt`

I am getting the below error:
```
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dbt--homebrew-virtualenv-20201117-44337-1irhflo/target --install-scripts=/private/
Last 15 lines from /Users/micwei/Library/Logs/Homebrew/dbt/05.python3:
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpygehl2m2', '--quiet', 'setuptools_scm>=2']' returned non-zero exit status 1.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/fishtown-analytics/homebrew-dbt/issues

These open issues may also help:
dbt fails with "image not found" https://github.com/fishtown-analytics/homebrew-dbt/issues/5
dbt install error https://github.com/fishtown-analytics/homebrew-dbt/issues/2

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/. 
```

I am running python 3.8.3 on macOS Catalina 10.15.7

**Comment by frankieeder** [comment]
I'm getting the same error on a client's machine. We've tried to reinstall the CLT multiple times using
`  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install`
but it does not fix the error.

**Comment by frankieeder** [comment]
update: we were able to succesfully install the older version of dbt by using
`brew install dbt@0.17.1-rc4`
so I presume this is an error from a recent update.


Here's the error we got when trying to run just `dbt install`
```
Last 15 lines from /Users/<<user>>/Library/Logs/Homebrew/dbt/05.python3:
  File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/usr/local/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    raise DistutilsError(str(e)) from e
distutils.errors.DistutilsError: Command '['/usr/local/opt/python@3.8/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmpztsyg4nu', '--quiet', 'setuptools_scm>=2']' returned non-zero exit status 2.
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/fishtown-analytics/homebrew-dbt/issues
These open issues may also help:
dbt fails with "image not found" https://github.com/fishtown-analytics/homebrew-dbt/issues/5
dbt install error https://github.com/fishtown-analytics/homebrew-dbt/issues/2
Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force
If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
```

Here's the machine environment:
```
$ python --version
Python 3.7.4
$ python3 --version
Python 3.7.4
$ python3.8 --version
Python 3.8.0
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force
If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /opt/anaconda3/bin/llvm-config
  /opt/anaconda3/bin/icu-config
  /opt/anaconda3/bin/krb5-config
  /opt/anaconda3/bin/freetype-config
  /opt/anaconda3/bin/xslt-config
  /opt/anaconda3/bin/libpng16-config
  /opt/anaconda3/bin/python3.7-config
  /opt/anaconda3/bin/libpng-config
  /opt/anaconda3/bin/xml2-config
  /opt/anaconda3/bin/python3.7m-config
  /opt/anaconda3/bin/gsl-config
  /opt/anaconda3/bin/python3-config
  /opt/anaconda3/bin/curl-config
  /opt/anaconda3/bin/ncursesw6-config
  /opt/anaconda3/bin/pcre-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8-config
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.
Unexpected dylibs:
  /usr/local/lib/libnnz11.dylib
  /usr/local/lib/libociei.dylib
  /usr/local/lib/libocijdbc11.dylib
Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  python@3.9
```
The machine is MacOS Mojave 10.14.5

**Comment by drewbanin** [comment]
Thanks for the reports, folks! @jtcohen6 - any idea what might be going wrong here?

**Comment by jtcohen6** [comment]
I'm not sure, no. I know I needed to manually update the default brew installation (#6), so it's possible I messed something up there.

@gboro54 @frankieeder Do you see the same error when you explicitly install one the newest version?
```
brew install dbt@0.18.1
```

**Comment by frankieeder** [comment]
> I'm not sure, no. I know I needed to manually update the default brew installation (#6), so it's possible I messed something up there.
> 
> @gboro54 @frankieeder Do you see the same error when you explicitly install the newest version?
> 
> ```
> brew install dbt@0.18.1
> ```

If we explicitly install the new version using the command you sent, it seems to install/update fine.

**Comment by dzifuta** [comment]
I'm getting the same issue when making `brew install dbt@0.18.1`. Installing `brew install dbt@0.18.0` went well, though. Any ideas on how to proceed? Should we consider some alternative path to install the latest version?

**Comment by jtcohen6** [comment]
@dzifuta You're seeing the same error as in the original post? Which version of macOS are you running?

In the meantime, the best alternative path to try would be `pip install dbt`.

**Comment by ldbrandi** [comment]
I'm getting this same error using Big Sur

**Comment by md-tran** [comment]
I'm also getting the same error, on dbt 0.19, Big Sur MacOS

**Comment by jtcohen6** [comment]
@ldbrandi @md-tran Could you share the version of python you're using, and the specific error messages you're seeing? Could you also confirm that you're able to install other programs (e.g. `postgresql`) using `brew`?

In the meantime, I'd also recommend trying `pip install dbt`.

**Comment by md-tran** [comment]
> @ldbrandi @md-tran Could you share the version of python you're using, and the specific error messages you're seeing? Could you also confirm that you're able to install other programs (e.g. `postgresql`) using `brew`?
> 
> In the meantime, I'd also recommend trying `pip install dbt`.

In fact, i realised i didn't need the development version - didn't read the docs properly. Thanks!

**Comment by meyerjoseph** [comment]
@jtcohen6 @drewbanin I am also running into issues installing dbt on the M1 chip for Big Sur. 

After following the documentation, when I run dbt --version, I get the following:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/dbt", line 5, in <module>
    from dbt.main import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dbt/main.py", line 11, in <module>
    import dbt.version
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dbt/version.py", line 100, in <module>
    installed = get_installed_version()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dbt/version.py", line 29, in get_installed_version
    return dbt.semver.VersionSpecifier.from_version_string(__version__)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dbt/semver.py", line 100, in from_version_string
    return cls.from_dict(matched)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 618, in from_dict
    cls.validate(data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 957, in validate
    schema = _validate_schema(cls)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 183, in _validate_schema
    schema = schema_cls.json_schema()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 942, in json_schema
    return cls._json_schema_recursive(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 913, in _json_schema_recursive
    schema = cls._schema_defs_from_cache(definitions)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 900, in _schema_defs_from_cache
    schema = cls._collect_json_schema(definitions)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 863, in _collect_json_schema
    properties[target_field], is_required = cls._get_field_schema(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 809, in _get_field_schema
    field_schema, required = cls._get_schema_for_type(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hologram/__init__.py", line 783, in _get_schema_for_type
    raise ValidationError(f"Unable to create schema for '{type_name}'")
hologram.ValidationError: Unable to create schema for 'Optional'

brew list --versions returns:
brew list --versions
dbt 0.19.1_1
dbt@0.19.1 0.19.1_1
gdbm 1.19
gettext 0.21
git 2.31.1
icu4c 69.1
krb5 1.19.1
libffi 3.3_3
libidn2 2.3.1
libssh2 1.9.0_1
libunistring 0.9.10
mpdecimal 2.5.1
openssl@1.1 1.1.1k
pcre2 10.37
pkg-config 0.29.2_3
postgresql 13.3
python@3.8 3.8.10
python@3.9 3.9.5
readline 8.1
rust 1.52.1
sqlite 3.35.5
tcl-tk 8.6.11_1
wget 1.21.1
xz 5.2.5

**Comment by jtcohen6** [comment]
@meyerjoseph Two things:

- dbt-snowflake==0.19.1 has dependencies that are not py39-compatible.
- It looks like you're installing an old version of hologram, which isn't py39-compatible either (the cause of the specific error message you're seeing)

Could you try installing the latest prerelease version of dbt, which should be py39-compatible across the board?
```
brew install dbt@0.20.0-rc1
brew link dbt@0.20.0-rc1
```

**Comment by meyerjoseph** [comment]
@jtcohen6 I am getting an error when I run brew install dbt@0.20.0-rc1

Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/dbt
Target /opt/homebrew/bin/dbt
is a symlink belonging to dbt@0.19.1. You can unlink it:
  brew unlink dbt@0.19.1

To force the link and overwrite all conflicting files:
  brew link --overwrite dbt@0.20.0-rc1

To list all files that would be deleted:
  brew link --overwrite --dry-run dbt@0.20.0-rc1

Possible conflicting files are:
/opt/homebrew/bin/dbt -> /opt/homebrew/Cellar/dbt@0.19.1/0.19.1_1/bin/dbt
==> Summary
🍺  /opt/homebrew/Cellar/dbt@0.20.0-rc1/0.20.0rc1_1: 9,813 files, 156.6MB, built in 4 minutes 53 seconds

Running the second command:
FL-PT-JM:~ (...me... too )$ brew link dbt@0.20.0-rc1
Linking /opt/homebrew/Cellar/dbt@0.20.0-rc1/0.20.0rc1_1...
Error: Could not symlink bin/dbt
Target /opt/homebrew/bin/dbt
is a symlink belonging to dbt@0.19.1. You can unlink it:
  brew unlink dbt@0.19.1

To force the link and overwrite all conflicting files:
  brew link --overwrite dbt@0.20.0-rc1

To list all files that would be deleted:
  brew link --overwrite --dry-run dbt@0.20.0-rc1

**Comment by jtcohen6** [comment]
@meyerjoseph That's good news! That means the installation completed successfully. You should then run:
```
brew link --overwrite dbt@0.20.0-rc1
```

**Comment by meyerjoseph** [comment]
@jtcohen6 Thanks for the follow up. Unfortunately I am still running into issues here. 

I can run dbt --version:

```
installed version: 0.20.0-rc1
   latest version: 0.19.1

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 0.20.0rc1
  - snowflake: 0.20.0rc1
  - redshift: 0.20.0rc1
  - postgres: 0.20.0rc1
```

However, when I try to run a model we (in this case we call it dim_clients), I get the original ffi.callback() error:
```
dbt run --m dim_clients --no-version-check
Running with dbt=0.20.0-rc1
* Deprecation Warning: The "packages" argument of adapter.dispatch() has been
deprecated. Use the "macro_namespace" argument instead.
Raised during dispatch for: except
For more information, see:
https://docs.getdbt.com/reference/dbt-jinja-functions/dispatch
[WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.snowplow.sessions.snowplow_sessions_tmp

Found 221 models, 377 tests, 1 snapshot, 0 analyses, 354 macros, 14 operations, 1 seed file, 103 sources, 0 exposures

Encountered an error:
Cannot allocate write+execute memory for ffi.callback(). You might be running on a system that prevents this. For more information, see https://cffi.readthedocs.io/en/latest/using.html#callbacks
```

**Comment by jtcohen6** [comment]
@meyerjoseph Ah, folks have been discussing that error over here: https://github.com/fishtown-analytics/dbt/issues/3162. It sounds like your Homebrew installation succeeded, but now there's a conflict between M1 and a dependency of `snowflake-connector-python`. Unfortunately, I think your best bet may be to try reinstalling dbt [via Rosetta](https://alexslobodnik.medium.com/apple-m1-python-pandas-and-homebrew-20f14828ccc7).
