### ISSUE TITLE
Unexpected dbt version

### ISSUE THREAD

**Issue by mirosval** [dbt-labs/homebrew-dbt#72]
Hello, I'm not sure if this is the right place to post this, but I'm experiencing some confusion with dbt versions.

When I install dbt with `brew install dbt-redshift@1.0.0`, the `dbt --version` reported is `1.0.1`. This is a problem, because the current docker image has dbt at version `1.0.0`. So when I want to use deferred state, it doesn't work because manifests created from Docker, don't work with dbt installed via Homebrew.

There doesn't seem to be any way to install version `1.0.0` via homebrew, as `dbt-redhsift` and `dbt-redshift@1.0.0` both install dbt `1.0.1`.

I'm also not really sure what the solution here is apart from advancing all versions to `1.0.2` at once, but I wanted to make sure this is on your radar.

**Comment by jtcohen6** [comment]
Hey @mirosval, thanks for opening the issue! There are a few things going on here:
- We will be updating the `latest` tags for Docker images, to use the latest available versions of `dbt-core` + plugins. That's a manual step today; we're working to add it as a coordinated step with the rest of our automated release process.
- Similarly, we will be updating the Homebrew formulae to use the latest available versions of `dbt-core` + each plugin. That's also a manual step today; it will be slightly trickier to integrate it with the rest of the release process, but still very much worth doing.
- There's another question baked in here: Should deferral/state comparison look at dbt minor versions (excluding patches), or artifact schema versions, as the basis for determining if two artifacts can be reasonably compared? The fixes we're making in patch releases after v1.0 are much narrower than previous patches, so it's worth asking the question—even if the (likely) answer is, still better safe than sorry.
