### ISSUE TITLE
Legacy install error / cffi on dot-snowflake installation for M1 chip

### ISSUE THREAD

**Issue by PS-Arrio** [dbt-labs/homebrew-dbt#81]
While the extractor issue looks to be resolved, I'm still experiencing an error:

Last 15 lines from /Users/arriohoffman/Library/Logs/Homebrew/dbt-snowflake/08.pip:
else:
filename = ""
setup_py_code = "from setuptools import setup; setup()"

exec(compile(setup_py_code, filename, "exec"))
'"'"''"'"''"'"' % ('"'"'/private/tmp/dbt-snowflake--cffi-20220318-6744-13qkt2q/cffi-1.15.0/setup.py'"'"',), "", "exec"))' install --record /private/tmp/pip-record-j_jq6e7u/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Homebrew/Cellar/dbt-snowflake/1.0.0_3/libexec/include/site/python3.9/cffi
cwd: /private/tmp/dbt-snowflake--cffi-20220318-6744-13qkt2q/cffi-1.15.0/
Running setup.py install for cffi: finished with status 'error'
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by jtcohen6** [comment]
@PS-Arrio Sorry for the long delay in response!

- Which version of `dbt-snowflake` were you trying to install?
- Any other relevant information about your system that you can provide?
